PackageIdentifier: ManticoreGames.Core
PackageName: Core
PackageVersion: 1.3.0.0
PackageLocale: en-US
Publisher: Manticore Games
License: Copyright © 2020 Manticore Games, Inc. All Rights Reserved.
ShortDescription: Core is an endless universe of games and worlds designed by a global community of creators.
InstallerType: exe
Installers:
  - Architecture: x64
    InstallerUrl: https://manticoreprod.azureedge.net/builds/CoreLauncherInstall.exe
    InstallerSha256: 69cbc014b759a1da9694e6ca31be802eb50b3ef75fbcd08ea7241415b6b54a7d
ManifestType: installer
ManifestVersion: 1.0.0
